data:
   image: busybox:latest
   ports:
     - "2280:22"
   volumes:
     - .:/var/www/blexr
   links:
     - db
   tty: true

fpm:
  build: docker/php
  volumes_from:
    - data
#  volumes:
#    - ./docker/php/:/usr/local/etc/php/
  expose:
    - 9000
  links:
    - db

nginx:
  image: nginx:latest
  volumes_from:
    - data
  ports:
    - "8080:80"
  volumes:
    - ./docker/nginx/:/etc/nginx/conf.d/
  links:
   - fpm

db:
    image: postgres:latest
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: blexr
      POSTGRES_PASSWORD: blexr
      POSTGRES_USER: blexr
